GET http://localhost:8080/categoria/all

###

POST http://localhost:8080/categoria/save
Content-Type: application/json

{
    "id": null,
    "nome": "CARTÃO"
}

###
POST http://localhost:8080/categoria/findById
Content-Type: application/json

{
    "id": 1,
    "nome": "Romildo"
}
